version: "3.6"
services:
    keycloak:
        build:
            context: docker
            args:
                KEYCLOAK_VERSION: ${KEYCLOAK_VERSION}
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: password
            KC_PROXY: edge
        ports:
            - "8080:8080"
